PV1       .equ 0xf003 ; parameter in regs, PVnr after call

FNCRT     .equ 0x00
FNCOLORUP .equ 0x0f
FNOSTR    .equ 0x23

CASS      .equ 0xb700
ARGC      .equ 0xb780
ARGN      .equ 0xb781
ARG1      .equ 0xb782
ARG2      .equ 0xb784
ARG3      .equ 0xb786
ARG4      .equ 0xb788
ARG5      .equ 0xb78a
ARG6      .equ 0xb78c
ARG7      .equ 0xb78e
ARG8      .equ 0xb790
ARG9      .equ 0xb792
ARG10     .equ 0xb794
NUMNX     .equ 0xb796
NUMVX     .equ 0xb797


